default['selenium']['bindings'] = { 'python' => '2.20.0' }
default['selenium']['server']['version'] = '2.20.0'
default['selenium']['server']['user'] = 'selenium'
default['selenium']['server']['installpath'] = '/opt'
default['selenium']['server']['logpath'] = '/var/log/selenium'
default['selenium']['server']['display'] = '17'
default['selenium']['server']['fbsize'] = '800x600x24'
default['selenium']['grid_version'] = '1.0.8'
default['selenium']['grid_port'] = '4444'
default['selenium']['chromedriver_version'] = '17.0.963.0'
